### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by aatng-gh** [aaronthangnguyen/cen4010-swe1#1]

**Comment by notrioht** [comment]
test

**Comment by murphybrenna** [comment]
Bmurp024@fiu.edu

**Comment by aatng-gh** [comment]
> [Bmurp024@fiu.edu](mailto:Bmurp024@fiu.edu)

There is no GitHub account associated with the email so I add this account into Collaborators list.

**Comment by murphybrenna** [comment]
Ok thank you!

**Comment by NassG1214** [comment]
giancarlonassi@gmail.com

**Comment by mariomossburg** [comment]
marmossburg@gmail.com

**Comment by VMNCgithub** [comment]
Navarroworld@gmail.com

**Comment by aatng-gh** [comment]
Everyone is fully present.
